# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 282c9586cfb2ec8276bed7142ec91433c57165b43156e3c285b70cd26479f5522062c7001c97ce7cb39cec0e8e42e15e879defe58ccaf29fe57188710c206790

test:
  secret_key_base: a1456658b77e6b515eb97dbed5a2e0f1c529f8a3fa22ddd7dccbecb33010d66c84945742ba961227ae7581bc05f57aa96bb4c9c84acd64b003d3847edcb498fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
